// *****************************************************************************
// * This is an automatically generated header file for UI Element definition  *
// * resource symbols and values. Please do not modify manually.               *
// *****************************************************************************

#pragma once

#define cmdButtonAbout 2 
#define cmdButtonAbout_LabelTitle_RESID 60001
#define cmdButtonAbout_LabelDescription_RESID 60002
#define cmdButtonAbout_TooltipTitle_RESID 60003
#define cmdButtonAbout_TooltipDescription_RESID 60004
#define cmdButtonAbout_SmallImages_192__RESID 60005
#define cmdButtonAbout_LargeImages_192__RESID 60006
#define cmdButtonOpenResponseCharts 3 
#define cmdButtonOpenResponseCharts_LabelTitle_RESID 60007
#define cmdButtonOpenResponseCharts_LabelDescription_RESID 60008
#define cmdButtonOpenResponseCharts_TooltipDescription_RESID 60009
#define cmdButtonOpenResponseCharts_SmallImages_192__RESID 60010
#define cmdButtonOpenResponseCharts_LargeImages_192__RESID 60011
#define cmdButtonOpenSnakeGame 4 
#define cmdButtonOpenSnakeGame_LabelTitle_RESID 60012
#define cmdButtonOpenSnakeGame_LabelDescription_RESID 60013
#define cmdButtonOpenSnakeGame_TooltipDescription_RESID 60014
#define cmdButtonOpenSnakeGame_SmallImages_192__RESID 60015
#define cmdButtonOpenSnakeGame_LargeImages_192__RESID 60016
#define cmdToggleSimulationExperiment 5 
#define cmdToggleSimulationExperiment_LabelTitle_RESID 60017
#define cmdToggleSimulationExperiment_TooltipTitle_RESID 60018
#define cmdToggleSimulationExperiment_TooltipDescription_RESID 60019
#define cmdToggleSimulationExperiment_SmallImages_192__RESID 60020
#define cmdToggleSimulationExperiment_LargeImages_192__RESID 60021
#define cmdButtonResetView 6 
#define cmdButtonResetView_LabelTitle_RESID 60022
#define cmdButtonResetView_LabelDescription_RESID 60023
#define cmdButtonResetView_TooltipDescription_RESID 60024
#define cmdButtonResetView_SmallImages_192__RESID 60025
#define cmdButtonResetView_LargeImages_192__RESID 60026
#define cmdButtonOpenModelDir 7 
#define cmdButtonOpenModelDir_LabelTitle_RESID 60027
#define cmdButtonOpenModelDir_LabelDescription_RESID 60028
#define cmdButtonOpenModelDir_TooltipDescription_RESID 60029
#define cmdButtonOpenModelDir_SmallImages_192__RESID 60030
#define cmdButtonOpenModelDir_LargeImages_192__RESID 60031
#define cmdButtonMakeScreenshot 8 
#define cmdButtonMakeScreenshot_LabelTitle_RESID 60032
#define cmdButtonMakeScreenshot_TooltipDescription_RESID 60033
#define cmdButtonMakeScreenshot_SmallImages_192__RESID 60034
#define cmdButtonMakeScreenshot_LargeImages_192__RESID 60035
#define cmdButtonOpenCanvas 9 
#define cmdButtonOpenCanvas_LabelTitle_RESID 60036
#define cmdButtonOpenCanvas_SmallImages_192__RESID 60037
#define cmdButtonOpenCanvas_LargeImages_192__RESID 60038
#define cmdToggleShowGroundGrid 10 
#define cmdToggleShowGroundGrid_LabelTitle_RESID 60039
#define cmdToggleShowGroundGrid_TooltipDescription_RESID 60040
#define cmdToggleShowGroundGrid_SmallImages_192__RESID 60041
#define cmdToggleShowGroundGrid_LargeImages_192__RESID 60042
#define cmdNumIntensity 11 
#define cmdNumIntensity_LabelTitle_RESID 60043
#define cmdNumSimulationSteps 12 
#define cmdNumSimulationSteps_LabelTitle_RESID 60044
#define cmdToggleShowConnection 13 
#define cmdToggleShowConnection_LabelTitle_RESID 60045
#define cmdToggleShowConnection_TooltipDescription_RESID 60046
#define cmdToggleShowConnection_SmallImages_192__RESID 60047
#define cmdToggleShowConnection_LargeImages_192__RESID 60048
#define cmdNumSynapseCutoff 14 
#define cmdNumSynapseCutoff_LabelTitle_RESID 60049
#define cmdNumScatterSize 15 
#define cmdNumScatterSize_LabelTitle_RESID 60050
#define cmdButtonExit 16 
#define cmdButtonExit_LabelTitle_RESID 60051
#define cmdButtonExit_SmallImages_192__RESID 60052
#define cmdButtonExit_LargeImages_192__RESID 60053
#define cmdGroupDisplayOptions 17 
#define cmdGroupDisplayOptions_LabelTitle_RESID 60054
#define cmdGroupInformation 18 
#define cmdGroupInformation_LabelTitle_RESID 60055
#define cmdGroupWorkbenchTools 19 
#define cmdGroupWorkbenchTools_LabelTitle_RESID 60056
#define cmdGroupWorkbench 20 
#define cmdGroupWorkbench_LabelTitle_RESID 60057
#define cmdMenuWorkbench 21 
#define cmdMenuWorkbench_LabelTitle_RESID 60058
#define cmdGroupDisplayParameters 22 
#define cmdGroupDisplayParameters_LabelTitle_RESID 60059
#define cmdGroupExperimentParameters 23 
#define cmdGroupExperimentParameters_LabelTitle_RESID 60060
#define cmdTabCanvasOptions 24 
#define cmdTabCanvasOptions_LabelTitle_RESID 60061
#define cmdMenuSimulationExperiment 25 
#define cmdMenuSimulationExperiment_LabelTitle_RESID 60062
#define cmdTabExperiment 26 
#define cmdTabExperiment_LabelTitle_RESID 60063
#define InternalCmd2_LabelTitle_RESID 60064
