'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports RibbonLib
Imports RibbonLib.Controls

Namespace RibbonLib.Controls
    Partial Class RibbonItems
        Private Class Cmd
            Public Const cmdButtonAbout As UInteger = 2
            Public Const cmdButtonExit As UInteger = 16
            Public Const cmdNumIntensity As UInteger = 11
            Public Const cmdNumSimulationSteps As UInteger = 12
            Public Const cmdButtonOpenModelDir As UInteger = 7
            Public Const cmdButtonMakeScreenshot As UInteger = 8
            Public Const cmdButtonOpenCanvas As UInteger = 9
            Public Const cmdButtonOpenResponseCharts As UInteger = 3
            Public Const cmdButtonOpenSnakeGame As UInteger = 4
            Public Const cmdToggleSimulationExperiment As UInteger = 5
            Public Const cmdButtonResetView As UInteger = 6
            Public Const cmdToggleShowGroundGrid As UInteger = 10
            Public Const cmdToggleShowConnection As UInteger = 13
            Public Const cmdNumSynapseCutoff As UInteger = 14
            Public Const cmdNumScatterSize As UInteger = 15
        End Class

        ' ContextPopup CommandName

        Private _ribbon As Ribbon
        Public ReadOnly Property Ribbon As Ribbon
            Get
                Return _ribbon
            End Get
        End Property
        Private _ButtonAbout As RibbonButton
        Public ReadOnly Property ButtonAbout As RibbonButton
            Get
                Return _ButtonAbout
            End Get
        End Property
        Private _ButtonExit As RibbonButton
        Public ReadOnly Property ButtonExit As RibbonButton
            Get
                Return _ButtonExit
            End Get
        End Property
        Private _NumIntensity As RibbonSpinner
        Public ReadOnly Property NumIntensity As RibbonSpinner
            Get
                Return _NumIntensity
            End Get
        End Property
        Private _NumSimulationSteps As RibbonSpinner
        Public ReadOnly Property NumSimulationSteps As RibbonSpinner
            Get
                Return _NumSimulationSteps
            End Get
        End Property
        Private _ButtonOpenModelDir As RibbonButton
        Public ReadOnly Property ButtonOpenModelDir As RibbonButton
            Get
                Return _ButtonOpenModelDir
            End Get
        End Property
        Private _ButtonMakeScreenshot As RibbonButton
        Public ReadOnly Property ButtonMakeScreenshot As RibbonButton
            Get
                Return _ButtonMakeScreenshot
            End Get
        End Property
        Private _ButtonOpenCanvas As RibbonButton
        Public ReadOnly Property ButtonOpenCanvas As RibbonButton
            Get
                Return _ButtonOpenCanvas
            End Get
        End Property
        Private _ButtonOpenResponseCharts As RibbonButton
        Public ReadOnly Property ButtonOpenResponseCharts As RibbonButton
            Get
                Return _ButtonOpenResponseCharts
            End Get
        End Property
        Private _ButtonOpenSnakeGame As RibbonButton
        Public ReadOnly Property ButtonOpenSnakeGame As RibbonButton
            Get
                Return _ButtonOpenSnakeGame
            End Get
        End Property
        Private _ToggleSimulationExperiment As RibbonToggleButton
        Public ReadOnly Property ToggleSimulationExperiment As RibbonToggleButton
            Get
                Return _ToggleSimulationExperiment
            End Get
        End Property
        Private _ButtonResetView As RibbonButton
        Public ReadOnly Property ButtonResetView As RibbonButton
            Get
                Return _ButtonResetView
            End Get
        End Property
        Private _ToggleShowGroundGrid As RibbonToggleButton
        Public ReadOnly Property ToggleShowGroundGrid As RibbonToggleButton
            Get
                Return _ToggleShowGroundGrid
            End Get
        End Property
        Private _ToggleShowConnection As RibbonToggleButton
        Public ReadOnly Property ToggleShowConnection As RibbonToggleButton
            Get
                Return _ToggleShowConnection
            End Get
        End Property
        Private _NumSynapseCutoff As RibbonSpinner
        Public ReadOnly Property NumSynapseCutoff As RibbonSpinner
            Get
                Return _NumSynapseCutoff
            End Get
        End Property
        Private _NumScatterSize As RibbonSpinner
        Public ReadOnly Property NumScatterSize As RibbonSpinner
            Get
                Return _NumScatterSize
            End Get
        End Property

        Public Sub New(ByVal ribbon As Ribbon)
            If ribbon Is Nothing Then
                Throw New ArgumentNullException(NameOf(ribbon), "Parameter is Nothing")
            End If
            _ribbon = ribbon
            _ButtonAbout = New RibbonButton(_ribbon, Cmd.cmdButtonAbout)
            _ButtonExit = New RibbonButton(_ribbon, Cmd.cmdButtonExit)
            _NumIntensity = New RibbonSpinner(_ribbon, Cmd.cmdNumIntensity)
            _NumSimulationSteps = New RibbonSpinner(_ribbon, Cmd.cmdNumSimulationSteps)
            _ButtonOpenModelDir = New RibbonButton(_ribbon, Cmd.cmdButtonOpenModelDir)
            _ButtonMakeScreenshot = New RibbonButton(_ribbon, Cmd.cmdButtonMakeScreenshot)
            _ButtonOpenCanvas = New RibbonButton(_ribbon, Cmd.cmdButtonOpenCanvas)
            _ButtonOpenResponseCharts = New RibbonButton(_ribbon, Cmd.cmdButtonOpenResponseCharts)
            _ButtonOpenSnakeGame = New RibbonButton(_ribbon, Cmd.cmdButtonOpenSnakeGame)
            _ToggleSimulationExperiment = New RibbonToggleButton(_ribbon, Cmd.cmdToggleSimulationExperiment)
            _ButtonResetView = New RibbonButton(_ribbon, Cmd.cmdButtonResetView)
            _ToggleShowGroundGrid = New RibbonToggleButton(_ribbon, Cmd.cmdToggleShowGroundGrid)
            _ToggleShowConnection = New RibbonToggleButton(_ribbon, Cmd.cmdToggleShowConnection)
            _NumSynapseCutoff = New RibbonSpinner(_ribbon, Cmd.cmdNumSynapseCutoff)
            _NumScatterSize = New RibbonSpinner(_ribbon, Cmd.cmdNumScatterSize)
        End Sub

    End Class
End Namespace
