'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports RibbonLib
Imports RibbonLib.Controls

Namespace RibbonLib.Controls
    Partial Class RibbonItems
        Private Class Cmd
            Public Const cmdButtonAbout As UInteger = 2
            Public Const cmdButtonOpenModelDir As UInteger = 7
            Public Const cmdButtonMakeScreenshot As UInteger = 8
            Public Const cmdButtonOpenCanvas As UInteger = 9
            Public Const cmdButtonOpenResponseCharts As UInteger = 3
            Public Const cmdButtonOpenSnakeGame As UInteger = 4
            Public Const cmdToggleSimulationExperiment As UInteger = 5
            Public Const cmdButtonResetView As UInteger = 6
        End Class

        ' ContextPopup CommandName

        Private _ribbon As Ribbon
        Public ReadOnly Property Ribbon As Ribbon
            Get
                Return _ribbon
            End Get
        End Property
        Private _ButtonAbout As RibbonButton
        Public ReadOnly Property ButtonAbout As RibbonButton
            Get
                Return _ButtonAbout
            End Get
        End Property
        Private _ButtonOpenModelDir As RibbonButton
        Public ReadOnly Property ButtonOpenModelDir As RibbonButton
            Get
                Return _ButtonOpenModelDir
            End Get
        End Property
        Private _ButtonMakeScreenshot As RibbonButton
        Public ReadOnly Property ButtonMakeScreenshot As RibbonButton
            Get
                Return _ButtonMakeScreenshot
            End Get
        End Property
        Private _ButtonOpenCanvas As RibbonButton
        Public ReadOnly Property ButtonOpenCanvas As RibbonButton
            Get
                Return _ButtonOpenCanvas
            End Get
        End Property
        Private _ButtonOpenResponseCharts As RibbonButton
        Public ReadOnly Property ButtonOpenResponseCharts As RibbonButton
            Get
                Return _ButtonOpenResponseCharts
            End Get
        End Property
        Private _ButtonOpenSnakeGame As RibbonButton
        Public ReadOnly Property ButtonOpenSnakeGame As RibbonButton
            Get
                Return _ButtonOpenSnakeGame
            End Get
        End Property
        Private _ToggleSimulationExperiment As RibbonToggleButton
        Public ReadOnly Property ToggleSimulationExperiment As RibbonToggleButton
            Get
                Return _ToggleSimulationExperiment
            End Get
        End Property
        Private _ButtonResetView As RibbonButton
        Public ReadOnly Property ButtonResetView As RibbonButton
            Get
                Return _ButtonResetView
            End Get
        End Property

        Public Sub New(ByVal ribbon As Ribbon)
            If ribbon Is Nothing Then
                Throw New ArgumentNullException(NameOf(ribbon), "Parameter is Nothing")
            End If
            _ribbon = ribbon
            _ButtonAbout = New RibbonButton(_ribbon, Cmd.cmdButtonAbout)
            _ButtonOpenModelDir = New RibbonButton(_ribbon, Cmd.cmdButtonOpenModelDir)
            _ButtonMakeScreenshot = New RibbonButton(_ribbon, Cmd.cmdButtonMakeScreenshot)
            _ButtonOpenCanvas = New RibbonButton(_ribbon, Cmd.cmdButtonOpenCanvas)
            _ButtonOpenResponseCharts = New RibbonButton(_ribbon, Cmd.cmdButtonOpenResponseCharts)
            _ButtonOpenSnakeGame = New RibbonButton(_ribbon, Cmd.cmdButtonOpenSnakeGame)
            _ToggleSimulationExperiment = New RibbonToggleButton(_ribbon, Cmd.cmdToggleSimulationExperiment)
            _ButtonResetView = New RibbonButton(_ribbon, Cmd.cmdButtonResetView)
        End Sub

    End Class
End Namespace
