//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using RibbonLib;
using RibbonLib.Controls;

namespace RibbonLib.Controls
{
    partial class RibbonItems
    {
        private static class Cmd
        {
            public const uint cmdButtonAbout = 2;
            public const uint cmdNumIntensity = 11;
            public const uint cmdNumSimulationSteps = 12;
            public const uint cmdButtonOpenModelDir = 7;
            public const uint cmdButtonMakeScreenshot = 8;
            public const uint cmdButtonOpenCanvas = 9;
            public const uint cmdButtonOpenResponseCharts = 3;
            public const uint cmdButtonOpenSnakeGame = 4;
            public const uint cmdToggleSimulationExperiment = 5;
            public const uint cmdButtonResetView = 6;
            public const uint cmdToggleShowGroundGrid = 10;
            public const uint cmdToggleShowConnection = 13;
            public const uint cmdNumSynapseCutoff = 14;
            public const uint cmdNumScatterSize = 15;
        }

        // ContextPopup CommandName

        public Ribbon Ribbon { get; private set; }
        public RibbonButton ButtonAbout { get; private set; }
        public RibbonSpinner NumIntensity { get; private set; }
        public RibbonSpinner NumSimulationSteps { get; private set; }
        public RibbonButton ButtonOpenModelDir { get; private set; }
        public RibbonButton ButtonMakeScreenshot { get; private set; }
        public RibbonButton ButtonOpenCanvas { get; private set; }
        public RibbonButton ButtonOpenResponseCharts { get; private set; }
        public RibbonButton ButtonOpenSnakeGame { get; private set; }
        public RibbonToggleButton ToggleSimulationExperiment { get; private set; }
        public RibbonButton ButtonResetView { get; private set; }
        public RibbonToggleButton ToggleShowGroundGrid { get; private set; }
        public RibbonToggleButton ToggleShowConnection { get; private set; }
        public RibbonSpinner NumSynapseCutoff { get; private set; }
        public RibbonSpinner NumScatterSize { get; private set; }

        public RibbonItems(Ribbon ribbon)
        {
            if (ribbon == null)
                throw new ArgumentNullException(nameof(ribbon), "Parameter is null");
            this.Ribbon = ribbon;
            ButtonAbout = new RibbonButton(ribbon, Cmd.cmdButtonAbout);
            NumIntensity = new RibbonSpinner(ribbon, Cmd.cmdNumIntensity);
            NumSimulationSteps = new RibbonSpinner(ribbon, Cmd.cmdNumSimulationSteps);
            ButtonOpenModelDir = new RibbonButton(ribbon, Cmd.cmdButtonOpenModelDir);
            ButtonMakeScreenshot = new RibbonButton(ribbon, Cmd.cmdButtonMakeScreenshot);
            ButtonOpenCanvas = new RibbonButton(ribbon, Cmd.cmdButtonOpenCanvas);
            ButtonOpenResponseCharts = new RibbonButton(ribbon, Cmd.cmdButtonOpenResponseCharts);
            ButtonOpenSnakeGame = new RibbonButton(ribbon, Cmd.cmdButtonOpenSnakeGame);
            ToggleSimulationExperiment = new RibbonToggleButton(ribbon, Cmd.cmdToggleSimulationExperiment);
            ButtonResetView = new RibbonButton(ribbon, Cmd.cmdButtonResetView);
            ToggleShowGroundGrid = new RibbonToggleButton(ribbon, Cmd.cmdToggleShowGroundGrid);
            ToggleShowConnection = new RibbonToggleButton(ribbon, Cmd.cmdToggleShowConnection);
            NumSynapseCutoff = new RibbonSpinner(ribbon, Cmd.cmdNumSynapseCutoff);
            NumScatterSize = new RibbonSpinner(ribbon, Cmd.cmdNumScatterSize);
        }

    }
}
