Imports Microsoft.VisualBasic.Data.Framework.StorageProvider.Reflection

Namespace FAFBv783

    ''' <summary>
    ''' Proofread Cell Names And Groups: ``names.csv.gz`` (139,255 rows, 3 columns).
    ''' 
    ''' Groups are assigned based on the brain regions with most in/out synapses of
    ''' the cell. Names are autogenerated from group + running id, while trying to
    ''' preserve consistency across data snapshot versions as much as possible.
    ''' </summary>
    Public Class CellNames

        <Column("root_id", GetType(Int64Parser))>
        Public Property RootId As Long

        ''' <summary>
        ''' Autogenerated name of the cell, for example ``LO.LOP.561``.
        ''' </summary>
        <Column("name")>
        Public Property Name As String

        ''' <summary>
        ''' Autogenerated group of the cell, for example ``LO.LOP``.
        ''' </summary>
        <Column("group")>
        Public Property Group As String

    End Class
End Namespace
