Imports Microsoft.VisualBasic.Data.Framework.StorageProvider.Reflection

Namespace FAFBv783

    ''' <summary>
    ''' Neurotransmitter Type Predictions: ``neurons.csv.gz`` (139,255 rows, 10 columns).
    ''' 
    ''' For every cell in the dataset, specifies auto-generated group (based on primary
    ''' input and output neuropils) as well as the predicted neurotransmitter type of
    ''' the cell along with the prediction scores for individual NT types.
    ''' </summary>
    Public Class Neurons

        <Column("root_id", GetType(Int64Parser))>
        Public Property RootId As Long

        ''' <summary>
        ''' Autogenerated group, based on the primary input and output neuropils.
        ''' </summary>
        <Column("group")>
        Public Property Group As String

        ''' <summary>
        ''' Predicted neurotransmitter type, for example ``ACH``; may be empty.
        ''' </summary>
        <Column("nt_type")>
        Public Property NtType As String

        <Column("nt_type_score")>
        Public Property NtTypeScore As Double

        <Column("da_avg")>
        Public Property DaAvg As Double

        <Column("ser_avg")>
        Public Property SerAvg As Double

        <Column("gaba_avg")>
        Public Property GabaAvg As Double

        <Column("glut_avg")>
        Public Property GlutAvg As Double

        <Column("ach_avg")>
        Public Property AchAvg As Double

        <Column("oct_avg")>
        Public Property OctAvg As Double

    End Class
End Namespace
